version: '3.3'
services:
  post_db:
    image: mongo:${post_db_tag}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${ui_tag}
    ports:
      - ${ui_host_port}:${ui_docker_port}
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${post_tag}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${comment_tag}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
